version: 2
services:
  TopoANode1:
    image: 10.77.70.142:5000/tenderminttopo:v0.4
    container_name: TopoANode1
    hostname: TopoANode1
    tty: true
    volumes: ['/home/centos/NFS500/networktopo/TopoANode1/config:/tendermint/config']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=f4b46deae5cb79fb130c017f836e4d822d6c59ab@TopoANode3:26656,498391d9a85b066e34b3ac7987e3991029680d8c@TopoANode2:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [ttAnode1]
  TopoANode2:
    image: 10.77.70.142:5000/tenderminttopo:v0.4
    container_name: TopoANode2
    hostname: TopoANode2
    tty: true
    volumes: ['/home/centos/NFS500/networktopo/TopoANode2/config:/tendermint/config']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=fa4a0a27e8a1655060e955252cfe1bb1d48bfcf3@TopoANode1:26656,44431a88f2f3e79e0a744bc077136773b9fd3843@TopoANode4:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [ttAnode2]
  TopoANode3:
    image: 10.77.70.142:5000/tenderminttopo:v0.4
    container_name: TopoANode3
    hostname: TopoANode3
    tty: true
    volumes: ['/home/centos/NFS500/networktopo/TopoANode3/config:/tendermint/config']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=fa4a0a27e8a1655060e955252cfe1bb1d48bfcf3@TopoANode1:26656,44431a88f2f3e79e0a744bc077136773b9fd3843@TopoANode4:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [ttAnode3]
  TopoANode4:
    image: 10.77.70.142:5000/tenderminttopo:v0.4
    container_name: TopoANode4
    hostname: TopoANode4
    tty: true
    volumes: ['/home/centos/NFS500/networktopo/TopoANode4/config:/tendermint/config']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=f4b46deae5cb79fb130c017f836e4d822d6c59ab@TopoANode3:26656,498391d9a85b066e34b3ac7987e3991029680d8c@TopoANode2:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore']
    networks:
      tendermintnet1:
        aliases: [ttAnode4]
