# 模板参数
# node_name： 节点名 （tt0s1）
# shard_name: 节点所属分片名 （0）
# image: 镜像名
# peers： tendermint连接句柄
# count： 片内节点总数 （4）
# node_num: 该节点在片内编号 （1）
# shard_num： 该分片编号 （0）
# thresholdd：聚合签名门限值 （2）
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {node_name}
  labels:
    name: {node_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shardingbc
  template:
    metadata:
      labels:
        app: shardingbc
        name: {node_name}
    spec:
      affinity: # 指定主机
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: mylabel
                operator: In
                values:
                - {shard_name}
      containers:
      - name: {node_name}
        image: {image}
        imagePullPolicy: Always
        command:
          - tendermint
          - node
          - --p2p.persistent_peers=${peers}
          - --moniker=`hostname`
          - --proxy_app=persistent_kvstore
        env:
          - name: Count
            value: "{count}"
          - name: TASKID
            value: "{shard_num}"
          - name: TASKINDEX 
            value: "{node_num}"
          - name: THRESHOLD
            value: "{threshold}"
        volumeMounts: # 卷挂载
          - mountPath: /tendermint/config
            name: vs{shard_num}{node_num}
        # resources: # 资源限制
        #   limits:
        #     cpu: "1"
        #     memory: 2Gi
      volumes: #挂载宿主机路径
        - hostPath:
            path: /home/centos/NFS500/network/{shard_num}S{node_num}/config
            type: ""
          name: vs{shard_num}{node_num}
---
kind: Service
apiVersion: v1
metadata:
  name:  {node_name}
  labels:
    name: {node_name}
spec:
  selector:
    name: {node_num}
  type:  ClusterIP
  ports:
  - name:  default
    port:  42
    targetPort:  42
  - name:  p6
    port:  26656
    targetPort:  26656
  - name:  p7
    port:  26657
    targetPort:  26657